include dracula.conf

# Font
font_family      FiraCode Nerd Font Mono Regular
bold_font        FiraCode Nerd Font Mono Bold
italic_font      FiraCode Nerd Font Mono Italic
bold_italic_font FiraCode Nerd Font Mono Italic Bold

font_size 12.0

# OS
macos_option_as_alt yes

macos_show_window_title_in window

macos_quit_when_last_window_closed no

# Mouse
url_style curly

# Shell integration
shell_integration no-cursor


#
# Key bindings
#

kitty_mod ctrl+shift
clear_all_shortcuts yes

# General
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+q quit
map cmd+, edit_config_file
map cmd+equal change_font_size all +2.0
map cmd+minus change_font_size all -2.0
